/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nils' at '03.12.16 12:58' with Gradle 2.10
 *
 * @author Nils, @date 03.12.16 12:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
